
import Head from 'next/head'

export default function Header() {
    return (
        <Head>
            <title>ESL GAME</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="#" />
        </Head>
    )
}
