export default {
    "month": [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November ",
        "December",
    ],
    "date": [
        "First",
        "Second",
        "Third",
        "Fourth",
        "Fifth",
        "Sixth",
        "Seventh",
        "Eighth",
        "Ninth",
        "Tenth",
        "Eleventh",
        "Twelfth",
        "Thirteenth",
        "Fourteenth",
        "Fifteenth",
        "Sixteenth",
        "Seventeenth",
        "Eighteenth",
        "Nineteenth",
        "Twentieth",
        "Twenty-first",
        "Twenty-second",
        "Twenty-third",
        "Twenty-fourth",
        "Twenty-fifth",
    ],
    "time": [
        "At eight o'clock",
        "At eight",
        "At a quater past eight",
        "At eight fifteen",
        "At half past eight",
        "At eight thirty",
        "At a quater to eight",
        "At seven forty-five"
    ]
}